//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrderProcessing_Complete
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderID { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string CustomerName { get; set; }
        public string CustomerAddress { get; set; }
        public string CustomerPhone { get; set; }
        public string TShirtColor { get; set; }
        public string TShirtSize { get; set; }
        public Nullable<decimal> TShirtPrice { get; set; }
        public Nullable<int> Quantity { get; set; }
        public Nullable<int> OrderTotal { get; set; }
        public int OrderStatusID { get; set; }
        public string Notes { get; set; }
    }
}
